const network= {
    "sequence":[
    {
        "duration":90,
        "introduction":["you are space travelers, exploring alien worlds. you can tap each object you discover to ask specific questions on it. you have landed at your first planet. you have sixty seconds to learn about it",["introduction_1_1.wav","introduction_1_2.wav","introduction_1_3.wav","introduction_1_4.wav"]],
        "type":"full",
        "network":"network_1",
        "n":0
    },
    {
        "duration":60,
        "introduction":["you have reached a new planet. you can tap each object you discover to ask specific questions on it. you have sixty seconds to learn about this planet",["introduction_2_1.wav","introduction_2_2.wav","introduction_2_3.wav"]],
        "type":"full",
        "network":"network_2",
        "n":0
    },
    {
        "duration":60,
        "introduction":["you have reached your third planet. you are in a hurry and have time to ask only five questions. choose them carefully.",["introduction_3_1.wav","introduction_3_2.wav","introduction_3_3.wav"]],
        "type":"n_questions",
        "network":"network_3",
        "n":5
    },
    {
        "duration":60,
        "introduction":["a new planet appears. you have limited access to knowledge about it. you can select a single question type, such as how, what or why, and find out only about it.",["introduction_4_1.wav","introduction_4_2.wav","introduction_4_3.wav"]],
        "type":"n_type",
        "network":"network_4",
        "n":1
    },
    {
        "duration":60,
        "introduction":["space travelers, you have reached the final planet. you have sixty seconds to learn about it before returning home.",["introduction_5_1.wav","introduction_5_2.wav"]],
        "type":"full",
        "network":"network_5",
        "n":0
    }],
    "edges":[
        {"source":"alien","edge":"q1","target":["concept_1_1","concept_1_2","concept_1_3","concept_1_4"]},
        {"source":"alien","edge":"q2","target":["concept_2_1"]},
        {"source":"alien","edge":"q3","target":["concept_3_1","concept_3_2"]},
        {"source":"concept_2_1","edge":"q1","target":["concept_1_1","concept_1_3"]},
        {"source":"concept_2_1","edge":"q2","target":["concept_4_1"]},
        {"source":"concept_2_1","edge":"q3","target":["concept_3_1","concept_3_3"]},
        {"source":"plant","edge":"q1","target":["concept_1_1","concept_1_3","concept_1_4","concept_1_5"]},
        {"source":"plant","edge":"q2","target":["concept_2_2"]},
        {"source":"plant","edge":"q3","target":["concept_3_3","concept_3_4"]},
        {"source":"concept_2_2","edge":"q1","target":["concept_1_1","concept_1_3"]},
        {"source":"concept_2_2","edge":"q2","target":["concept_4_2"]},
        {"source":"concept_2_2","edge":"q3","target":["concept_3_4","concept_3_5"]},
        {"source":"tech","edge":"q1","target":["concept_1_1","concept_1_2","concept_1_3","concept_1_5"]},
        {"source":"tech","edge":"q2","target":["concept_2_3"]},
        {"source":"tech","edge":"q3","target":["concept_3_1","concept_3_4"]},
        {"source":"concept_2_3","edge":"q1","target":["concept_1_2","concept_1_4"]},
        {"source":"concept_2_3","edge":"q2","target":["concept_4_3"]},
        {"source":"concept_2_3","edge":"q3","target":["concept_3_3","concept_3_5"]}
    ],   
    "questions":{
        "how":{"image":"how_he.png","explanation":["whenever you press the how button, you get information about the question how does this work",["how_explanation.wav"]],"pos":0.0},
        "what":{"image":"what_he.png","explanation":["whenever you press the what button, you get information about the question what is this made out of",["what_explanation.wav"]],"pos":0.1},
        "why":{"image":"why_he.png","explanation":["whenever you press the why button, you get information about the question why is it here",["why_explanation.wav"]],"pos":0.2},
        "general":{"pos":0.01,"size":"0.2,0.2"}
    },
    "network_1":{
        "story":{
            "what,why,how":{ // original 
                "plant,what":["the plants are made of four different types of colorful cells",["1_plants_what1.wav"]],
                "alien,what":["the aliens are made of four different types of colorful cells",["1_aliens_what1.wav"]],
                "tech,what":["the spaceship is made of four different types of colorful cells",["1_spaceship_what1.wav"]],
                "reason_1,what":["the grand city is made of two different types of colorful cells",["1_grand_city_what1.wav"]],
                "reason_2,what":["the cute animals are made of two different types of colorful cells",["1_cute_animals_what1.wav"]],
                "reason_3,what":["the grey city is made of two different types of colorful cells",["1_grey_city_what1.wav"]],

                "plant,why":["the plants are here to feed the cute animals",["1_plants_why2.wav"]],
                "alien,why":["the aliens are here to build their grand city in the hills",["1_aliens_why2.wav"]],
                "tech,why":["the spaceship is here to transport aliens from the grey city",["1_spaceship_why2.wav"]],
                "reason_1,why":["the grand city is built to make the aliens happy",["1_grand_city_why2.wav"]],
                "reason_2,why":["the cute animals are here to feed to nasty animals",["1_cute_animals_why2.wav"]],
                "reason_3,why":["the grey city is here to take the aliens to the moon",["1_grey_city_why2.wav"]],

                "plant,how":["the plants work by channeling the flow between two orbs",["1_plants_how3.wav"]],
                "alien,how":["the aliens work by channeling the flow between two orbs",["1_aliens_how3.wav"]],
                "tech,how":["the spaceship works by channeling the flow between two orbs",["1_spaceship_how3.wav"]],
                "reason_1,how":["the city works by channeling the flow between two orbs",["1_grand_city_how3.wav"]],
                "reason_2,how":["the cute animals work by channeling the flow between two orbs",["1_cute_animals_how3.wav"]],
                "reason_3,how":["the grey city works by channeling the flow between two orbs",["1_grey_city_how3.wav"]]
            },
            "what,how,why":{ // #1 switched why and how from original 
                "plant,what":["the plants are made of four different types of colorful cells",["1_plants_what1.wav"]],
                "alien,what":["the aliens are made of four different types of colorful cells",["1_aliens_what1.wav"]],
                "tech,what":["the spaceship is made of four different types of colorful cells",["1_spaceship_what1.wav"]],
                "reason_1,what":["the grand city is made of two different types of colorful cells",["1_grand_city_what1.wav"]],
                "reason_2,what":["the cute animals are made of two different types of colorful cells",["1_cute_animals_what1.wav"]],
                "reason_3,what":["the grey city is made of two different types of colorful cells",["1_grey_city_what1.wav"]],

                "plant,how":["the plants grow with the help of the cute animals",["1_plants_how2.wav"]],
                "alien,how":["the aliens work with mechanical parts from the grand city in the hills",["1_aliens_how2.wav"]],
                "tech,how":["the spaceship works with mechanical processes from the grey city",["1_spaceship_how2.wav"]],
                "reason_1,how":["the grand city works only when the aliens are happy",["1_grand_city_how2.wav"]],
                "reason_2,how":["the cute animals work by copying the nasty animals",["1_cute_animals_how2.wav"]],
                "reason_3,how":["the grey city works with energy from the moon",["1_grey_city_how2.wav"]],

                "plant,why":["the plants are here to give oxygen to the orbs",["1_plants_why3.wav"]],
                "alien,why":["the aliens here to find a way to fly to the floating orbs",["1_aliens_why3.wav"]],
                "tech,why":["the spaceship is here to transport the aliens to the orbs",["1_spaceship_why3.wav"]],
                "reason_1,why":["the city is here to shine light on the floating orbs",["1_grand_city_why3.wav"]],
                "reason_2,why":["the cute animals are here to find pieces of grass that fell from the orbs",["1_cute_animals_why3.wav"]],
                "reason_3,why":["the grey city is here to harvest energy from the two orbs",["1_grey_city_why3.wav"]]
            },
            "why,what,how":{ // #2 switched what and why from original 
                "plant,why":["the plants are here to make four different types of colorful cells",["1_plants_why1.wav"]],
                "alien,why":["the aliens are here to find four different types of colorful cells",["1_aliens_why1.wav"]],
                "tech,why":["the spaceship is here to transport four different types of colorful cells",["1_spaceship_why1.wav"]],
                "reason_1,why":["the grand city is here to make two different types of colorful cells",["1_grand_city_why1.wav"]],
                "reason_2,why":["the cute animals are here to eat two different types of colorful cells",["1_cute_animals_why1.wav"]],
                "reason_3,why":["the grey city is here to make two different types of colorful cells",["1_grey_city_why1.wav"]],

                "plant,what":["the plants are made of the cute animals poop",["1_plants_what2.wav"]],
                "alien,what":["the aliens are made of parts that were built in the grand city in the hills",["1_aliens_what2.wav"]],
                "tech,what":["the spaceship is made of parts built in the grey city",["1_spaceship_what2.wav"]],
                "reason_1,what":["the grand city is made of happy places for the happy aliens",["1_grand_city_what2.wav"]],
                "reason_2,what":["the cute animals the children of the nasty animals",["1_cute_animals_what2.wav"]],
                "reason_3,what":["the grey city is made of rocks from the moon",["1_grey_city_what2.wav"]],

                "plant,how":["the plants work by channeling the flow between two orbs",["1_plants_how3.wav"]],
                "alien,how":["the aliens work by channeling the flow between two orbs",["1_aliens_how3.wav"]],
                "tech,how":["the spaceship works by channeling the flow between two orbs",["1_spaceship_how3.wav"]],
                "reason_1,how":["the city works by channeling the flow between two orbs",["1_grand_city_how3.wav"]],
                "reason_2,how":["the cute animals work by channeling the flow between two orbs",["1_cute_animals_how3.wav"]],
                "reason_3,how":["the grey city works by channeling the flow between two orbs",["1_grey_city_how3.wav"]]
            },
            "why,how,what":{ // #3 switched what and how from #2
                "plant,why":["the plants are here to make four different types of colorful cells",["1_plants_why1.wav"]],
                "alien,why":["the aliens are here to find four different types of colorful cells",["1_aliens_why1.wav"]],
                "tech,why":["the spaceship is here to transport four different types of colorful cells",["1_spaceship_why1.wav"]],
                "reason_1,why":["the grand city is here to make two different types of colorful cells",["1_grand_city_why1.wav"]],
                "reason_2,why":["the cute animals are here to eat two different types of colorful cells",["1_cute_animals_why1.wav"]],
                "reason_3,why":["the grey city is here to make two different types of colorful cells",["1_grey_city_why1.wav"]],

                "plant,how":["the plants grow with the help of the cute animals",["1_plants_how2.wav"]],
                "alien,how":["the aliens work with mechanical parts from the grand city in the hills",["1_aliens_how2.wav"]],
                "tech,how":["the spaceship works with mechanical processes from the grey city",["1_spaceship_how2.wav"]],
                "reason_1,how":["the grand city works only when the aliens are happy",["1_grand_city_how2.wav"]],
                "reason_2,how":["the cute animals work by copying the nasty animals",["1_cute_animals_how2.wav"]],
                "reason_3,how":["the grey city works with energy from the moon",["1_grey_city_how2.wav"]],

                "plant,what":["the plants are made of seeds from two orbs",["1_plants_what3.wav"]],
                "alien,what":["the aliens are made of mechanical parts from two orbs",["1_aliens_what3.wav"]],
                "tech,what":["the spaceship is made of rocks from two orbs",["1_spaceship_what3.wav"]],
                "reason_1,what":["the city is made of rocks and pieces from two orbs",["1_grand_city_what3.wav"]],
                "reason_2,what":["the cute animals are made of special material from two orbs",["1_cute_animals_what3.wav"]],
                "reason_3,what":["the grey city is made of rocks from two orbs",["1_grey_city_what3.wav"]]
            },                
            "how,why,what":{ // #4 switched how and what from original 
                "plant,how":["the plants work with the energy from four types of colorful cells",["1_plants_how1.wav"]],
                "alien,how":["the aliens work with the energy from four different types of colorful cells",["1_aliens_how1.wav"]],
                "tech,how":["the spaceship works with the energy from four different types of colorful cells",["1_spaceship_how1.wav"]],
                "reason_1,how":["the grand city works with the energy from two different types of colorful cells",["1_grand_city_how1.wav"]],
                "reason_2,how":["the cute animals work with the energy from two different types of colorful cells",["1_cute_animals_how1.wav"]],
                "reason_3,how":["the grey city works with the energy from two different types of colorful cells",["1_grey_city_how1.wav"]],

                "plant,why":["the plants are here to feed the cute animals",["1_plants_why2.wav"]],
                "alien,why":["the aliens are here to build their grand city in the hills",["1_aliens_why2.wav"]],
                "tech,why":["the spaceship is here to transport aliens from the grey city",["1_spaceship_why2.wav"]],
                "reason_1,why":["the grand city is built to make the aliens happy",["1_grand_city_why2.wav"]],
                "reason_2,why":["the cute animals are here to feed to nasty animals",["1_cute_animals_why2.wav"]],
                "reason_3,why":["the grey city is here to take the aliens to the moon",["1_grey_city_why2.wav"]],

                "plant,what":["the plants are made of seeds from two orbs",["1_plants_what3.wav"]],
                "alien,what":["the aliens are made of mechanical parts from two orbs",["1_aliens_what3.wav"]],
                "tech,what":["the spaceship is made of rocks from two orbs",["1_spaceship_what3.wav"]],
                "reason_1,what":["the city is made of rocks and pieces from two orbs",["1_grand_city_what3.wav"]],
                "reason_2,what":["the cute animals are made of special material from two orbs",["1_cute_animals_what3.wav"]],
                "reason_3,what":["the grey city is made of rocks from two orbs",["1_grey_city_what3.wav"]]
            },
            "how,what,why":{ // #5 switched why and what from #4 
                "plant,how":["the plants work with the energy from four types of colorful cells",["1_plants_how1.wav"]],
                "alien,how":["the aliens work with the energy from four different types of colorful cells",["1_aliens_how1.wav"]],
                "tech,how":["the spaceship works with the energy from four different types of colorful cells",["1_spaceship_how1.wav"]],
                "reason_1,how":["the grand city works with the energy from two different types of colorful cells",["1_grand_city_how1.wav"]],
                "reason_2,how":["the cute animals work with the energy from two different types of colorful cells",["1_cute_animals_how1.wav"]],
                "reason_3,how":["the grey city works with the energy from two different types of colorful cells",["1_grey_city_how1.wav"]],

                "plant,what":["the plants are made of the cute animals poop",["1_plants_what2.wav"]],
                "alien,what":["the aliens are made of parts that were built in the grand city in the hills",["1_aliens_what2.wav"]],
                "tech,what":["the spaceship is made of parts built in the grey city",["1_spaceship_what2.wav"]],
                "reason_1,what":["the grand city is made of happy places for the happy aliens",["1_grand_city_what2.wav"]],
                "reason_2,what":["the cute animals the children of the nasty animals",["1_cute_animals_what2.wav"]],
                "reason_3,what":["the grey city is made of rocks from the moon",["1_grey_city_what2.wav"]],

                "plant,why":["the plants are here to give oxygen to the orbs",["1_plants_why3.wav"]],
                "alien,why":["the aliens here to find a way to fly to the floating orbs",["1_aliens_why3.wav"]],
                "tech,why":["the spaceship is here to transport the aliens to the orbs",["1_spaceship_why3.wav"]],
                "reason_1,why":["the city is here to shine light on the floating orbs",["1_grand_city_why3.wav"]],
                "reason_2,why":["the cute animals are here to find pieces of grass that fell from the orbs",["1_cute_animals_why3.wav"]],
                "reason_3,why":["the grey city is here to harvest energy from the two orbs",["1_grey_city_why3.wav"]]
            }
        },
        "background":"background1.png",
        "dir":"items/world1/",
        "concepts":
            {"reason_1":{"image":["app_all_city_2.png"],"level":2,"pos":"0.9, 0.62","size":"0.201, 0.133"},
            "reason_3":{"image":["app_all_city_1.png"],"level":2,"pos":"0.6, 0.65","size":"0.16, 0.12"},
            "reason_2":{"image":["animal3.png"],"level":2,"pos":"0.35, 0.22","size":"0.235, 0.216"},
            "reason_5":{"image":["app_all_city_2.png"],"level":2,"pos":"0.9, 0.62","size":"0.201, 0.133"},
            "reason_4":{"image":["app_all_city_2.png"],"level":2,"pos":"0.9, 0.62","size":"0.201, 0.133"},
            "process_5":{"image":["how_5_2.png","how_5_1.png"],"level":2,"pos":"0.08, 0.887","size":"0.089, 0.090"},
            "process_4":{"image":["how_4_2.png","how_4_1.png"],"level":2,"pos":"0.2, 0.887","size":"0.114, 0.116"},
            "process_3":{"image":["how_3_2.png","how_3_1.png"],"level":2,"pos":"0.32, 0.887","size":"0.104, 0.119"},
            "process_2":{"image":["how_2_2.png","how_2_1.png"],"level":2,"pos":"0.44, 0.887","size":"0.094, 0.125"},
            "process_1":{"image":["how_1_2.png","how_1_1.png"],"level":2,"pos":"0.56, 0.887","size":"0.151, 0.236"},
            "process_extend_3":{"image":["moon.png"],"level":2,"pos":"0.82, 0.82","size":"0.223, 0.195"},
            "process_extend_2":{"image":["moon.png"],"level":2,"pos":"0.82, 0.82","size":"0.223, 0.195"},
            "process_extend_1":{"image":["moon.png"],"level":2,"pos":"0.82, 0.82","size":"0.223, 0.195"},
            "plant":{"image":["plant1.png"],"level":1,"pos":"0.15, 0.33","size":"0.225, 0.390"},
            "part_extend_2":{"image":["what_cell9.png"],"level":2,"pos":"0.46, 0.7","size":"0.114, 0.159"},
            "part_extend_3":{"image":["what_cell9.png"],"level":2,"pos":"0.46, 0.7","size":"0.114, 0.159"},
            "part_extend_1":{"image":["what_cell9.png"],"level":2,"pos":"0.46, 0.7","size":"0.114, 0.159"},
            "reason_extend_1":{"image":["smiley_face.png"],"level":3,"pos":"0.4, 0.481","size":"0.104, 0.144"},
            "alien":{"image":["alien1.png"],"level":1,"pos":"0.65, 0.3","size":"0.353, 0.425"},
            "reason_extend_3":{"image":["moon.png"],"level":2,"pos":"0.82, 0.82","size":"0.223, 0.195"},
            "reason_extend_2":{"image":["aligator.png"],"level":3,"pos":"0.85, 0.25","size":"0.300, 0.203"},
            "tech":{"image":["tech1.png"],"level":1,"pos":"0.716, 0.75","size":"0.095, 0.173"},
            "part_1":{"image":["what_cell1.png"],"level":2,"pos":"0.06, 0.7","size":"0.114, 0.158"},
            "part_2":{"image":["what_cell2.png"],"level":2,"pos":"0.16, 0.7","size":"0.114, 0.158"},
            "part_3":{"image":["what_cell3.png"],"level":2,"pos":"0.26, 0.7","size":"0.114, 0.158"},
            "part_4":{"image":["what_cell7.png"],"level":2,"pos":"0.36, 0.7","size":"0.114, 0.159"},
            "part_5":{"image":["what_cell9.png"],"level":2,"pos":"0.46, 0.7","size":"0.114, 0.159"}
        }
    },
    "network_2":{
        "story":{
            "what,why,how":{ // original
                "plant,what":["the trees are made of four different types of circular objects",["2_trees_what1.wav"]],
                "tech,what":["the spaceship is made of four different circular objects",["2_spaceship_what1.wav"]],
                "alien,what":["the aliens are made of different circular objects",["2_aliens_what1.wav"]],
                "reason_1,what":["their planet was made of two different circular objects",["2_home_planet_what1.wav"]],
                "reason_2,what":["the cute animals are made of different types of circular objects",["2_cute_animals_what1.wav"]],
                "reason_3,what":["the spaceport is made of different circular objects",["2_spacestation_what1.wav"]],

                "plant,why":["the trees are here to feed the cute animals",["2_trees_why2.wav"]],
                "tech,why":["the spaceship is here to transport aliens to the spaceport",["2_spaceship_why2.wav"]],
                "alien,why":["the aliens are here because their world was destroyed",["2_aliens_why2.wav"]],
                "reason_1,why":["their old planet was destroyed by a powerful weapon",["2_home_planet_why2.wav"]],
                "reason_2,why":["the cute animals are here produce crystals",["2_cute_animals_why2.wav"]],
                "reason_3,why":["the spaceport is here to bring asteroid minerals to the factories",["2_spacestation_why2.wav"]],

                "plant,how":["the trees work by rotating discs",["2_trees_how3.wav"]],
                "tech,how":["the spaceship work by rotating discs",["2_spaceship_how3.wav"]],
                "alien,how":["the aliens work by rotating discs",["2_aliens_how3.wav"]],
                "reason_1,how":["the planet was maintained by rotating discs",["2_home_planet_how3.wav"]],
                "reason_2,how":["the cute animals work by rotating discs",["2_cute_animals_how3.wav"]],
                "reason_3,how":["the spaceport work by rotating discs",["2_spacestation_how3.wav"]] 
            },
            "what,how,why":{ // #1 swtiched why and how from original
                "plant,what":["the trees are made of four different types of circular objects",["2_trees_what1.wav"]],
                "tech,what":["the spaceship is made of four different circular objects",["2_spaceship_what1.wav"]],
                "alien,what":["the aliens are made of different circular objects",["2_aliens_what1.wav"]],
                "reason_1,what":["their planet was made of two different circular objects",["2_home_planet_what1.wav"]],
                "reason_2,what":["the cute animals are made of different types of circular objects",["2_cute_animals_what1.wav"]],
                "reason_3,what":["the spaceport is made of different circular objects",["2_spacestation_what1.wav"]],

                "plant,how":["the trees grow with the help of the cute animals",["2_trees_how2.wav"]],
                "tech,how":["the spaceship works by recieving energy from the spaceport",["2_spaceship_how2.wav"]],
                "alien,how":["the aliens live off of energy from the destroyed planet",["2_aliens_how2.wav"]],
                "reason_1,how":["the old planet worked with the energy from a strong weapon ",["2_home_planet_how2.wav"]],
                "reason_2,how":["the cute animals grow by eating colorful crystals",["2_cute_animals_how2.wav"]],
                "reason_3,how":["the spaceport works with mechanical parts from the factories",["2_spacestation_how2.wav"]],

                "plant,why":["the trees are here to produce rotating discs",["2_trees_why3.wav"]],
                "tech,why":["the spaceship is here to transport the rotating discs",["2_spaceship_why3.wav"]],
                "alien,why":["the aliens are here to find the rotating discs",["2_aliens_why3.wav"]],
                "reason_1,why":["the planet was here to produce rotating discs",["2_home_planet_why3.wav"]],
                "reason_2,why":["the cute animals are here to rotate the planets discs",["2_cute_animals_why3.wav"]],
                "reason_3,why":["the spaceport is here to shelter the rotating discs",["2_spacestation_why3.wav"]] 
            },
            "why,what,how":{ // #2 switched what and why from original
                "plant,why":["the trees are here to hold up the circular objects",["2_trees_why1.wav"]],
                "tech,why":["the spaceship is here to help the aliens catch the flying circular objects",["2_spaceship_why1.wav"]],
                "alien,why":["the aliens are here to find the flying circular objects",["2_aliens_why1.wav"]],
                "reason_1,why":["their planet was there to make different circular objects",["2_home_planet_why1.wav"]],
                "reason_2,why":["the cute animals are here to make circular objects",["2_cute_animals_why1.wav"]],
                "reason_3,why":["the spaceport is here to help the flying circular objects land",["2_spacestation_why1.wav"]],

                "plant,what":["the trees are made of the cute animals garbage",["2_trees_what2.wav"]],
                "tech,what":["the spaceship is is made of parts from the spaceport",["2_spaceship_what2.wav"]],
                "alien,what":["the aliens are made from the old world that was destroyed",["2_aliens_what2.wav"]],
                "reason_1,what":["their old planet was made of thousands of tiny and powerful weapons",["2_home_planet_what2.wav"]],
                "reason_2,what":["the cute animals are made of colorful crystals",["2_cute_animals_what2.wav"]],
                "reason_3,what":["the spaceport is made of mechanical parts from the factories",["2_spacestation_what2.wav"]],

                "plant,how":["the trees work by rotating discs",["2_trees_how3.wav"]],
                "tech,how":["the spaceship work by rotating discs",["2_spaceship_how3.wav"]],
                "alien,how":["the aliens work by rotating discs",["2_aliens_how3.wav"]],
                "reason_1,how":["the planet was maintained by rotating discs",["2_home_planet_how3.wav"]],
                "reason_2,how":["the cute animals work by rotating discs",["2_cute_animals_how3.wav"]],
                "reason_3,how":["the spaceport work by rotating discs",["2_spacestation_how3.wav"]]  
            },
            "why,how,what":{ // #3 switched what and how from #2
                "plant,why":["the trees are here to hold up the circular objects",["2_trees_why1.wav"]],
                "tech,why":["the spaceship is here to help the aliens catch the flying circular objects",["2_spaceship_why1.wav"]],
                "alien,why":["the aliens are here to find the flying circular objects",["2_aliens_why1.wav"]],
                "reason_1,why":["their planet was there to make different circular objects",["2_home_planet_why1.wav"]],
                "reason_2,why":["the cute animals are here to make circular objects",["2_cute_animals_why1.wav"]],
                "reason_3,why":["the spaceport is here to help the flying circular objects land",["2_spacestation_why1.wav"]],

                "plant,how":["the trees grow with the help of the cute animals",["2_trees_how2.wav"]],
                "tech,how":["the spaceship works by recieving energy from the spaceport",["2_spaceship_how2.wav"]],
                "alien,how":["the aliens live off of energy from the destroyed planet",["2_aliens_how2.wav"]],
                "reason_1,how":["the old planet worked with the energy from a strong weapon ",["2_home_planet_how2.wav"]],
                "reason_2,how":["the cute animals grow by eating colorful crystals",["2_cute_animals_how2.wav"]],
                "reason_3,how":["the spaceport works with mechanical parts from the factories",["2_spacestation_how2.wav"]],

                "plant,what":["the trees are made of rotating discs",["2_trees_what3.wav"]],
                "tech,what":["the spaceship is made of the fastest rotating discs",["2_spaceship_what3.wav"]],
                "alien,what":["the aliens are made of rotating discs",["2_aliens_what3.wav"]],
                "reason_1,what":["the old planet was made of rotating discs",["2_home_planet_what3.wav"]],
                "reason_2,what":["the cute animals are made of rotating discs",["2_cute_animals_what3.wav"]],
                "reason_3,what":["the spaceport is made of old rotating discs",["2_spacestation_what3.wav"]]  
            },
            "how,why,what":{ // #4 switched how and what from original
                "plant,how":["the trees grow from the power of four different circular objects",["2_trees_how1.wav"]],
                "tech,how":["the spaceship can only fly with the help of the circular objects",["2_spaceship_how1.wav"]],
                "alien,how":["the aliens work by eating different circular objects",["2_aliens_how1.wav"]],
                "reason_1,how":["their planet was maintained by two different circular objects",["2_home_planet_how1.wav"]],
                "reason_2,how":["the cute animals grow by eating the planets circular objects",["2_cute_animals_how1.wav"]],
                "reason_3,how":["the spaceport works with the energy from the circular objects",["2_spacestation_how1.wav"]],

                "plant,why":["the trees are here to feed the cute animals",["2_trees_why2.wav"]],
                "tech,why":["the spaceship is here to transport aliens to the spaceport",["2_spaceship_why2.wav"]],
                "alien,why":["the aliens are here because their world was destroyed",["2_aliens_why2.wav"]],
                "reason_1,why":["their old planet was destroyed by a powerful weapon",["2_home_planet_why2.wav"]],
                "reason_2,why":["the cute animals are here produce crystals",["2_cute_animals_why2.wav"]],
                "reason_3,why":["the spaceport is here to bring asteroid minerals to the factories",["2_spacestation_why2.wav"]],

                "plant,what":["the trees are made of rotating discs",["2_trees_what3.wav"]],
                "tech,what":["the spaceship is made of the fastest rotating discs",["2_spaceship_what3.wav"]],
                "alien,what":["the aliens are made of rotating discs",["2_aliens_what3.wav"]],
                "reason_1,what":["the old planet was made of rotating discs",["2_home_planet_what3.wav"]],
                "reason_2,what":["the cute animals are made of rotating discs",["2_cute_animals_what3.wav"]],
                "reason_3,what":["the spaceport is made of old rotating discs",["2_spacestation_what3.wav"]]  
            },
            "how,what,why":{ // #5 switched why and what from #4
                "plant,how":["the trees grow from the power of four different circular objects",["2_trees_how1.wav"]],
                "tech,how":["the spaceship can only fly with the help of the circular objects",["2_spaceship_how1.wav"]],
                "alien,how":["the aliens work by eating different circular objects",["2_aliens_how1.wav"]],
                "reason_1,how":["their planet was maintained by two different circular objects",["2_home_planet_how1.wav"]],
                "reason_2,how":["the cute animals grow by eating the planets circular objects",["2_cute_animals_how1.wav"]],
                "reason_3,how":["the spaceport works with the energy from the circular objects",["2_spacestation_how1.wav"]],

                "plant,what":["the trees are made of the cute animals garbage",["2_trees_what2.wav"]],
                "tech,what":["the spaceship is is made of parts from the spaceport",["2_spaceship_what2.wav"]],
                "alien,what":["the aliens are made from the old world that was destroyed",["2_aliens_what2.wav"]],
                "reason_1,what":["their old planet was made of thousands of tiny and powerful weapons",["2_home_planet_what2.wav"]],
                "reason_2,what":["the cute animals are made of colorful crystals",["2_cute_animals_what2.wav"]],
                "reason_3,what":["the spaceport is made of mechanical parts from the factories",["2_spacestation_what2.wav"]],

                "plant,why":["the trees are here to produce rotating discs",["2_trees_why3.wav"]],
                "tech,why":["the spaceship is here to transport the rotating discs",["2_spaceship_why3.wav"]],
                "alien,why":["the aliens are here to find the rotating discs",["2_aliens_why3.wav"]],
                "reason_1,why":["the planet was here to produce rotating discs",["2_home_planet_why3.wav"]],
                "reason_2,why":["the cute animals are here to rotate the planets discs",["2_cute_animals_why3.wav"]],
                "reason_3,why":["the spaceport is here to shelter the rotating discs",["2_spacestation_why3.wav"]] 
            }
        },
        "background":"app2_background.png",
        "dir":"items/world2/",
        "concepts":{
            "reason_1":{"image":["origin_planet.png"],"level":2,"pos":"0.9, 0.9","size":"0.16, 0.210"},
            "reason_3":{"image":["structures15.png"],"level":2,"pos":"0.75, 0.3","size":"0.2, 0.45"},
            "reason_2":{"image":["animal2_6.png"],"level":2,"pos":"0.35, 0.22","size":"0.127, 0.360"},
            "reason_5":{"image":["crystals4.png"],"level":2,"pos":"0.92, 0.2","size":"0.159, 0.250"},
            "reason_4":{"image":["crystals4.png"],"level":2,"pos":"0.92, 0.2","size":"0.159, 0.250"},
            "process_5":{"image":["how_4.png"],"level":2,"pos":"0.57, 0.85","size":"0.16, 0.20"},
            "process_4":{"image":["how_3.png"],"level":2,"pos":"0.29, 0.850","size":"0.16, 0.20"},
            "process_3":{"image":["how_2.png"],"level":2,"pos":"0.15, 0.850","size":"0.16, 0.20"},
            "process_2":{"image":["how_5_1.png","how_5_2.png"],"level":2,"pos":"0.710, 0.850","size":"0.16, 0.20"},
            "process_1":{"image":["how_1_1.png","how_1_2.png"],"level":2,"pos":"0.43, 0.850","size":"0.16, 0.20"},
            "process_extend_3":{"image":["how_4.png"],"level":2,"pos":"0.57, 0.85","size":"0.16, 0.20"},
            "process_extend_2":{"image":["how_4.png"],"level":2,"pos":"0.57, 0.85","size":"0.16, 0.20"},
            "process_extend_1":{"image":["how_4.png"],"level":2,"pos":"0.57, 0.85","size":"0.16, 0.20"},
            "plant":{"image":["plant.png"],"level":1,"pos":"0.065, 0.27","size":"0.174, 0.416"},
            "part_extend_2":{"image":["what_cell3.png"],"level":2,"pos":"0.08, 0.65","size":"0.16, 0.2"},
            "part_extend_3":{"image":["what_cell3.png"],"level":2,"pos":"0.08, 0.65","size":"0.16, 0.2"},
            "part_extend_1":{"image":["what_cell3.png"],"level":2,"pos":"0.08, 0.65","size":"0.16, 0.2"},
            "reason_extend_1":{"image":["weapon.png"],"level":3,"pos":"0.65, 0.3","size":"0.131, 0.217"},
            "alien":{"image":["alien.png"],"level":1,"pos":"0.55, 0.26","size":"0.326, 0.343"},
            "reason_extend_3":{"image":["structures9.png"],"level":2,"pos":"0.22, 0.265","size":"0.16, 0.25"},
            "reason_extend_2":{"image":["crystals4.png"],"level":3,"pos":"0.92, 0.2","size":"0.159, 0.250"},
            "tech":{"image":["tech.png"],"level":1,"pos":"0.9, 0.7","size":"0.3, 0.3"},
            "part_1":{"image":["what_cell3.png"],"level":2,"pos":"0.08, 0.65","size":"0.16, 0.2"},
            "part_2":{"image":["what_cell6.png"],"level":2,"pos":"0.22, 0.65","size":"0.16, 0.2"},
            "part_3":{"image":["what_cell10.png"],"level":2,"pos":"0.36, 0.65","size":"0.16, 0.2"},
            "part_4":{"image":["what_cell13.png"],"level":2,"pos":"0.50, 0.65","size":"0.16, 0.2"},
            "part_5":{"image":["what_cell15.png"],"level":2,"pos":"0.64, 0.65","size":"0.16, 0.2"}
        }
    },
    "network_3":{
        "story":{
            "what,why,how":{ // original
                "plant,what":["the flowers are made of different geometrical shapes",["3_flowers_what1.wav"]],
                "reason_1,what":["the cube is made of different geometrical shapes",["3_cube_what1.wav"]],
                "reason_2,what":["the factories are composed of different geometrical shapes",["3_factories_what1.wav"]],
                "reason_3,what":["the rocks are made of different geometrical shapes",["3_rocks_what1.wav"]],
                "tech,what":["the weapon is made of different geometrical shapes",["3_weapon_what1.wav"]],
                "alien,what":["the aliens are made of different geometrical shapes",["3_aliens_what1.wav"]],

                "plant,why":["the flowers are here to combat the factories pollution",["3_flowers_why2.wav"]],                   
                "reason_1,why":["the cube is here to help take over all worlds",["3_cube_why2.wav"]],                    
                "reason_2,why":["the factories are here to generate energy",["3_factories_why2.wav"]],                   
                "reason_3,why":["the rocks are here to protect the wild creatures",["3_rocks_why2.wav"]],                   
                "tech,why":["the weapon is here to blast rocks",["3_weapon_why2.wav"]],
                "alien,why":["the aliens are here to build the cube",["3_aliens_why2.wav"]],

                "plant,how":["the flowers work by internal colorful processes",["3_flowers_how3.wav"]],
                "reason_1,how":["the cube work by internal colorful processes",["3_cube_how3.wav"]],
                "reason_2,how":["the factories work by internal colorful processes",["3_factories_how3.wav"]],
                "reason_3,how":["the rocks work by colorful dynamic processes",["3_rocks_how3.wav"]],
                "tech,how":["the weapon work by colorful dynamic processes",["3_weapon_how3.wav"]],
                "alien,how":["the aliens work by colorful processes",["3_aliens_how3.wav"]]
            },
            "what,how,why":{ // #1 switched why and how from original
                "plant,what":["the flowers are made of different geometrical shapes",["3_flowers_what1.wav"]],
                "reason_1,what":["the cube is made of different geometrical shapes",["3_cube_what1.wav"]],
                "reason_2,what":["the factories are composed of different geometrical shapes",["3_factories_what1.wav"]],
                "reason_3,what":["the rocks are made of different geometrical shapes",["3_rocks_what1.wav"]],
                "tech,what":["the weapon is made of different geometrical shapes",["3_weapon_what1.wav"]],
                "alien,what":["the aliens are made of different geometrical shapes",["3_aliens_what1.wav"]],
                
                "plant,how":["the flowers work from light from the factories",["3_flowers_how2.wav"]],                   
                "reason_1,how":["the cube works from energy from all the worlds",["3_cube_how2.wav"]],                    
                "reason_2,how":["the factories work from the planets energy",["3_factories_how2.wav"]],                   
                "reason_3,how":["the rocks can move from the wild creatures energy",["3_rocks_how2.wav"]],                   
                "tech,how":["the weapon works by shooting rocks",["3_weapon_how2.wav"]],
                "alien,how":["the aliens can only live with the energy of the cube",["3_aliens_how2.wav"]],

                "plant,why":["the flowers here to make colorful processes",["3_flowers_why3.wav"]],
                "reason_1,why":["the cube is here to make colorful processes",["3_cube_why3.wav"]],
                "reason_2,why":["the factories are here to process the energy from the colorful processes",["3_factories_why3.wav"]],
                "reason_3,why":["the rocks are here to help the colorful processes shine",["3_rocks_why3.wav"]],
                "tech,why":["the weapon is here to help the aliens destroy the colorful processes",["3_weapon_why3.wav"]],
                "alien,why":["the aliens are here to destroy the colorful processes",["3_aliens_why3.wav"]]
            },
            "how,why,what":{ // #2 switched how and what from original 
                "plant,how":["the flowers grow with the energy from different geometrical shapes",["3_flowers_how1.wav"]],
                "reason_1,how":["the cube works from the energy of different geometrical shapes",["3_cube_how1.wav"]],
                "reason_2,how":["the factories work with the help of the planets geometrical shapes",["3_factories_how1.wav"]],
                "reason_3,how":["the rocks can move with the energy from different geometrical shapes",["3_rocks_how1.wav"]],
                "tech,how":["the weapon collects its energy from the geometrical shapes",["3_weapon_how1.wav"]],
                "alien,how":["the aliens live from the power of the geometrical shapes",["3_aliens_how1.wav"]],

                "plant,why":["the flowers are here to combat the factories pollution",["3_flowers_why2.wav"]],                   
                "reason_1,why":["the cube is here to help take over all worlds",["3_cube_why2.wav"]],                    
                "reason_2,why":["the factories are here to generate energy",["3_factories_why2.wav"]],                   
                "reason_3,why":["the rocks are here to hide the wild creatures",["3_rocks_why2.wav"]],                   
                "tech,why":["the weapon is here to blast rocks",["3_weapon_why2.wav"]],
                "alien,why":["the aliens are here to build the cube",["3_aliens_why2.wav"]],

                "plant,what":["the flowers are made of colorful processes",["3_flowers_what3.wav"]],
                "reason_1,what":["the cube is made of small colorful processes",["3_cube_what3.wav"]],
                "reason_2,what":["the factories are made of thousands of colorful processes",["3_factories_what3.wav"]],
                "reason_3,what":["the rocks are made of colorful dynamic processes",["3_rocks_what3.wav"]],
                "tech,what":["the weapon is made of colorful dynamic processes",["3_weapon_what3.wav"]],
                "alien,what":["the aliens are made of internal colorful processes",["3_aliens_what3.wav"]]
            },
            "how,what,why":{ // #3 switched why and what from #2 
                "plant,how":["the flowers grow with the energy from different geometrical shapes",["3_flowers_how1.wav"]],
                "reason_1,how":["the cube works from the energy of different geometrical shapes",["3_cube_how1.wav"]],
                "reason_2,how":["the factories work with the help of the planets geometrical shapes",["3_factories_how1.wav"]],
                "reason_3,how":["the rocks can move with the energy from different geometrical shapes",["3_rocks_how1.wav"]],
                "tech,how":["the weapon collects its energy from the geometrical shapes",["3_weapon_how1.wav"]],
                "alien,how":["the aliens live from the power of the geometrical shapes",["3_aliens_how1.wav"]],
                
                "plant,what":["the flowers are made of the factories pollution",["3_flowers_what2.wav"]],                   
                "reason_1,what":["the cube is made of energy from all the worlds",["3_cube_what2.wav"]],                    
                "reason_2,what":["the factories are made of generated energy",["3_factories_what2.wav"]],                   
                "reason_3,what":["the rocks are made of the wild creatures poop",["3_rocks_what2.wav"]],                   
                "tech,what":["the weapon is made of rocks",["3_weapon_what2.wav"]],
                "alien,what":["the aliens are made of energy from the cube",["3_aliens_what2.wav"]],

                "plant,why":["the flowers here to make colorful processes",["3_flowers_why3.wav"]],
                "reason_1,why":["the cube is here to make colorful processes",["3_cube_why3.wav"]],
                "reason_2,why":["the factories are here to process the energy from colorful processes",["3_factories_why3.wav"]],
                "reason_3,why":["the rocks are here to help the colorful processes shine",["3_rocks_why3.wav"]],
                "tech,why":["the weapon is here to help the aliens destroy the colorful processes",["3_weapon_why3.wav"]],
                "alien,why":["the aliens are here to destroy the colorful processes",["3_aliens_why3.wav"]]
            },
            "why,what,how":{ // #4 switched why and what from the original
                "plant,why":["the flowers are here to make different geometrical shapes",["3_flowers_why1.wav"]],
                "reason_1,why":["the cube is here to destroy the geometrical shapes",["3_cube_why1.wav"]],
                "reason_2,why":["the factories are here to make new geometrical shapes",["3_factories_why1.wav"]],
                "reason_3,why":["the rocks are here to replace the geometrical shapes if they are destroyed",["3_rocks_why1.wav"]],
                "tech,why":["the weapon is here to help the aliens save the geometrical shapes",["3_weapon_why1.wav"]],
                "alien,why":["the aliens are here to save different geometrical shapes",["3_aliens_why1.wav"]],

                "plant,what":["the flowers are made of the factories pollution",["3_flowers_what2.wav"]],                   
                "reason_1,what":["the cube is made of energy from all the worlds",["3_cube_what2.wav"]],                    
                "reason_2,what":["the factories are made of generated energy",["3_factories_what2.wav"]],                   
                "reason_3,what":["the rocks are made of the wild creatures poop",["3_rocks_what2.wav"]],                   
                "tech,what":["the weapon is made of rocks",["3_weapon_what2.wav"]],
                "alien,what":["the aliens are made of energy from the cube",["3_aliens_what2.wav"]],
                
                "plant,how":["the flowers work by internal colorful processes",["3_flowers_how3.wav"]],
                "reason_1,how":["the cube work by internal colorful processes",["3_cube_how3.wav"]],
                "reason_2,how":["the factories work by internal colorful processes",["3_factories_how3.wav"]],
                "reason_3,how":["the rocks work by colorful dynamic processes",["3_rocks_how3.wav"]],
                "tech,how":["the weapon work by colorful dynamic processes",["3_weapon_how3.wav"]],
                "alien,how":["the aliens work by colorful processes",["3_aliens_how3.wav"]]
            },
            "why,how,what":{ // #5 switched how and what from the #4
                "plant,why":["the flowers are here to make different geometrical shapes",["3_flowers_why1.wav"]],
                "reason_1,why":["the cube is here to destroy the geometrical shapes",["3_cube_why1.wav"]],
                "reason_2,why":["the factories are here to make new geometrical shapes",["3_factories_why1.wav"]],
                "reason_3,why":["the rocks are here to replace the geometrical shapes if they are destroyed",["3_rocks_why1.wav"]],
                "tech,why":["the weapon is here to help the aliens save the geometrical shapes",["3_weapon_why1.wav"]],
                "alien,why":["the aliens are here to save different geometrical shapes",["3_aliens_why1.wav"]],

                "plant,how":["the flowers work from light from the factories",["3_flowers_how2.wav"]],                   
                "reason_1,how":["the cube works from energy from all the worlds",["3_cube_how2.wav"]],                    
                "reason_2,how":["the factories work from the planets energy",["3_factories_how2.wav"]],                   
                "reason_3,how":["the rocks can move from the wild creatures energy",["3_rocks_how2.wav"]],                   
                "tech,how":["the weapon works by shooting rocks",["3_weapon_how2.wav"]],
                "alien,how":["the aliens can only live with the energy of the cube",["3_aliens_how2.wav"]],

                "plant,what":["the flowers are made of colorful processes",["3_flowers_what3.wav"]],
                "reason_1,what":["the cube is made of small colorful processes",["3_cube_what3.wav"]],
                "reason_2,what":["the factories are made of thousands of colorful processes",["3_factories_what3.wav"]],
                "reason_3,what":["the rocks are made of colorful dynamic processes",["3_rocks_what3.wav"]],
                "tech,what":["the weapon is made of colorful dynamic processes",["3_weapon_what3.wav"]],
                "alien,what":["the aliens are made of internal colorful processes",["3_aliens_what3.wav"]]
            }
        },
        "background":"background.png","dir":"items/world3/",
        "concepts":{
            "reason_1":{"image":["alien_reason.png"],"level":2,"pos":"0.82, 0.64","size":"0.15, 0.185"},
            "reason_3":{"image":["tech_reason_2.png","tech_reason_1.png"],"level":2,"pos":"0.9, 0.9","size":"0.168, 0.223"},
            "reason_2":{"image":["plant_reason.png"],"level":2,"pos":"0.717, 0.35","size":"0.25, 0.292"},
            "reason_5":{"image":["alien_reason.png"],"level":2,"pos":"0.82, 0.64","size":"0.15, 0.185"},
            "reason_4":{"image":["alien_reason.png"],"level":2,"pos":"0.82, 0.64","size":"0.15, 0.185"},
            "process_5":{"image":["what_cell8png.png"],"level":2,"pos":"0.5, 0.85","size":"0.155, 0.185"},
            "process_4":{"image":["what_cell9png.png"],"level":2,"pos":"0.64, 0.85","size":"0.155, 0.185"},
            "process_3":{"image":["what_cell7png.png"],"level":2,"pos":"0.36, 0.85","size":"0.155, 0.185"},
            "process_2":{"image":["what_cell5png.png"],"level":2,"pos":"0.22, 0.85","size":"0.155, 0.185"},
            "process_1":{"image":["what_cell3.png"],"level":2,"pos":"0.08, 0.85","size":"0.147, 0.185"},
            "process_extend_3":{"image":["what_cell8png.png"],"level":2,"pos":"0.5, 0.85","size":"0.155, 0.185"},
            "process_extend_2":{"image":["what_cell8png.png"],"level":2,"pos":"0.5, 0.85","size":"0.155, 0.185"},
            "process_extend_1":{"image":["what_cell8png.png"],"level":2,"pos":"0.5, 0.85","size":"0.155, 0.185"},
            "plant":{"image":["plant.png"],"level":1,"pos":"0.08, 0.25","size":"0.202, 0.285"},
            "part_extend_2":{"image":["geometrical_shapes1.png"],"level":2,"pos":"0.2, 0.65","size":"0.1, 0.16"},
            "part_extend_3":{"image":["geometrical_shapes1.png"],"level":2,"pos":"0.20, 0.65","size":"0.1, 0.16"},
            "part_extend_1":{"image":["geometrical_shapes1.png"],"level":2,"pos":"0.20, 0.65","size":"0.1, 0.16"},
            "reason_extend_1":{"image":["cube_reason.png"],"level":3,"pos":"0.52, 0.63","size":"0.161, 0.242"},
            "alien":{"image":["alien.png"],"level":1,"pos":"0.54, 0.28","size":"0.309, 0.494"},
            "reason_extend_3":{"image":["rock_reason.png"],"level":2,"pos":"0.25, 0.25","size":"0.301, 0.314"},
            "reason_extend_2":{"image":["factory_reason.png"],"level":3,"pos":"0.9, 0.182","size":"0.248, 0.164"},
            "tech":{"image":["tech.png"],"level":1,"pos":"0.58, 0.43","size":"0.131, 0.217"},
            "part_1":{"image":["geometrical_shapes1.png"],"level":2,"pos":"0.20, 0.65","size":"0.1, 0.16"},
            "part_2":{"image":["geometrical_shapes4.png"],"level":2,"pos":"0.08, 0.65","size":"0.1, 0.16"},
            "part_3":{"image":["geometrical_shapes7.png"],"level":2,"pos":"0.26, 0.52","size":"0.1, 0.16"},
            "part_4":{"image":["geometrical_shapes9.png"],"level":2,"pos":"0.32, 0.65","size":"0.1, 0.16"},
            "part_5":{"image":["geometrical_shapes10.png"],"level":2,"pos":"0.14, 0.52","size":"0.1, 0.16"}
        }
    },
    "network_4":{
        "story":{
            "what,why,how":{ // original 
                "alien,what":["the aliens are made of different electrical components",["4_aliens_what1.wav"]],
                "plant,what":["the robotic plants are made of electrical components",["4_robotic_plants_what1.wav"]],
                "tech,what":["the telecsope is made of electrical components",["4_telescope_what1.wav"]],
                "reason_1,what":["the chips are made of different electrical components",["4_chips_what1.wav"]],
                "reason_2,what":["the light catchers are made of electrical components",["4_light_what1.wav"]],
                "reason_3,what":["the new technologies are made of different electrical components",["4_tech_what1.wav"]],

                "alien,why":["the aliens are here to evolve to chips",["4_aliens_why2.wav"]],
                "plant,why":["the plants are here to enable light manipulation",["4_robotic_plants_why2.wav"]],
                "tech,why":["the telescope is here to discover new technologies",["4_telescope_why2.wav"]],
                "reason_1,why":["the chips are here to enable high processing power",["4_chips_why2.wav"]],
                "reason_2,why":["the the light catchers are here to harvest the sun",["4_light_why2.wav"]],
                "reason_3,why":["the new technologies are here to take the aliens to the stars",["4_tech_why2.wav"]],

                "alien,how":["the aliens work by electrical and mechanical process",["4_aliens_how3.wav"]],
                "plant,how":["the robotic plants work by electrical and mechanical process",["4_robotic_plants_how3.wav"]],
                "tech,how":["the telescope work by electrical and mechanical process",["4_telescope_how3.wav"]],
                "reason_1,how":["the chips work by electrical and mechanical process",["4_chips_how3.wav"]],
                "reason_2,how":["the light catchers work by electrical and mechanical process",["4_light_how3.wav"]],
                "reason_3,how":["the new technologies also work by electrical and mechanical process",["4_tech_how3.wav"]]
            },
            "what,how,why":{ // #1 switched why and how from original 
                "alien,what":["the aliens are made of different electrical components",["4_aliens_what1.wav"]],
                "plant,what":["the robotic plants are made of electrical components",["4_robotic_plants_what1.wav"]],
                "tech,what":["the telecsope is made of electrical components",["4_telescope_what1.wav"]],
                "reason_1,what":["the chips are made of different electrical components",["4_chips_what1.wav"]],
                "reason_2,what":["the light catchers are made of electrical components",["4_light_what1.wav"]],
                "reason_3,what":["the new technologies are made of different electrical components",["4_tech_what1.wav"]],

                "alien,how":["the aliens work by eletrical chips",["4_aliens_how2.wav"]],
                "plant,how":["the plants work by light manipulation",["4_robotic_plants_how2.wav"]],
                "tech,how":["the telescope works by new technologies",["4_telescope_how2.wav"]],
                "reason_1,how":["the chips are powered by high processing power",["4_chips_how2.wav"]],
                "reason_2,how":["the the light catchers are powered by light harvested form the sun",["4_light_how2.wav"]],
                "reason_3,how":["the new technologies are powered by forces from the stars",["4_tech_how2.wav"]],

                "alien,why":["the aliens are here to build electrical and mechanical process",["4_aliens_why3.wav"]],
                "plant,why":["the robotic plants are here to make electrical and mechanical process",["4_robotic_plants_why3.wav"]],
                "tech,why":["the telescope is here to find electrical and mechanical process",["4_telescope_why3.wav"]],
                "reason_1,why":["the chips are here to build electrical and mechanical process",["4_chips_why3.wav"]],
                "reason_2,why":["the light catchers are here to power electrical and mechanical process",["4_light_why3.wav"]],
                "reason_3,why":["the new technologies where created to build electrical and mechanical process",["4_tech_why3.wav"]]
            },
            "how,what,why":{ // #2 switched how and what from #1  
                "alien,how":["the aliens work by different electrical components",["4_aliens_how1.wav"]],
                "plant,how":["the robotic plants work by different electrical components",["4_robotic_plants_how1.wav"]],
                "tech,how":["the telecsope works by different electrical components",["4_telescope_how1.wav"]],
                "reason_1,how":["the chips work by accessing different electrical components",["4_chips_how1.wav"]],
                "reason_2,how":["the light catchers work by electrical components",["4_light_how1.wav"]],
                "reason_3,how":["the new technologies work by different electrical components",["4_tech_how1.wav"]],

                "alien,what":["the aliens are made of different electrical chips",["4_aliens_what2.wav"]],
                "plant,what":["the plants are made of light manipulation",["4_robotic_plants_what2.wav"]],
                "tech,what":["the telescope is here to discover new technologies",["4_telescope_what2.wav"]],
                "reason_1,what":["the chips are made of high processing power",["4_chips_what2.wav"]],
                "reason_2,what":["the the light catchers are made of power harvested from the sun",["4_light_what2.wav"]],
                "reason_3,what":["the new technologies are made from materials from the stars",["4_tech_what2.wav"]],

                "alien,why":["the aliens are here to build electrical and mechanical process",["4_aliens_why3.wav"]],
                "plant,why":["the robotic plants are here to make electrical and mechanical process",["4_robotic_plants_why3.wav"]],
                "tech,why":["the telescope is here to find electrical and mechanical process",["4_telescope_why3.wav"]],
                "reason_1,why":["the chips are here to build electrical and mechanical process",["4_chips_why3.wav"]],
                "reason_2,why":["the light catchers are here to power electrical and mechanical process",["4_light_why3.wav"]],
                "reason_3,why":["the new technologies where created to build electrical and mechanical process",["4_tech_why3.wav"]]
            },
            "how,why,what":{ // #3 switched how and what from original  
                "alien,how":["the aliens work by different electrical components",["4_aliens_how1.wav"]],
                "plant,how":["the robotic plants work by different electrical components",["4_robotic_plants_how1.wav"]],
                "tech,how":["the telecsope works by different electrical components",["4_telescope_how1.wav"]],
                "reason_1,how":["the chips work by accessing different electrical components",["4_chips_how1.wav"]],
                "reason_2,how":["the light catchers work by electrical components",["4_light_how1.wav"]],
                "reason_3,how":["the new technologies work by different electrical components",["4_tech_how1.wav"]],

                "alien,why":["the aliens are here to evolve to chips",["4_aliens_why2.wav"]],
                "plant,why":["the plants are here to enable light manipulation",["4_robotic_plants_why2.wav"]],
                "tech,why":["the telescope is here to discover new technologies",["4_telescope_why2.wav"]],
                "reason_1,why":["the chips are here to enable high processing power",["4_chips_why2.wav"]],
                "reason_2,why":["the the light catchers are here to harvest the sun",["4_light_why2.wav"]],
                "reason_3,why":["the new technologies are here to take the aliens to the stars",["4_tech_why2.wav"]],

                "alien,what":["the aliens are made of electrical and mechanical process",["4_aliens_what3.wav"]],
                "plant,what":["the robotic plants are made of electrical and mechanical process",["4_robotic_plants_what3.wav"]],
                "tech,what":["the telescope is made of new electrical and mechanical process",["4_telescope_what3.wav"]],
                "reason_1,what":["the chips are made of electrical and mechanical process",["4_chips_what3.wav"]],
                "reason_2,what":["the light catchers are made from electrical and mechanical process",["4_light_what3.wav"]],
                "reason_3,what":["the new technologies are made of electrical and mechanical process",["4_tech_what3.wav"]] 
            },
            "why,what,how":{ // #4 switched why and what from original
                "alien,why":["the aliens are here to make different electrical components",["4_aliens_why1.wav"]],
                "plant,why":["the robotic plants create electrical components",["4_robotic_plants_why1.wav"]],
                "tech,why":["the telecsope is here to find electrical components",["4_telescope_why1.wav"]],
                "reason_1,why":["the chips are here to build different electrical components",["4_chips_why1.wav"]],
                "reason_2,why":["the light catchers are here to produce electrical components",["4_light_why1.wav"]],
                "reason_3,why":["the new technologies are here to create different electrical components",["4_tech_why1.wav"]],

                "alien,what":["the aliens are made of different electrical chips",["4_aliens_what2.wav"]],
                "plant,what":["the plants are made of light manipulation",["4_robotic_plants_what2.wav"]],
                "tech,what":["the telescope is here to discover new technologies",["4_telescope_what2.wav"]],
                "reason_1,what":["the chips are made of high processing power",["4_chips_what2.wav"]],
                "reason_2,what":["the the light catchers are made of power harvested from the sun",["4_light_what2.wav"]],
                "reason_3,what":["the new technologies are made from materials from the stars",["4_tech_what2.wav"]],

                "alien,how":["the aliens work by electrical and mechanical process",["4_aliens_how3.wav"]],
                "plant,how":["the robotic plants work by electrical and mechanical process",["4_robotic_plants_how3.wav"]],
                "tech,how":["the telescope work by electrical and mechanical process",["4_telescope_how3.wav"]],
                "reason_1,how":["the chips work by electrical and mechanical process",["4_chips_how3.wav"]],
                "reason_2,how":["the light catchers work by electrical and mechanical process",["4_light_how3.wav"]],
                "reason_3,how":["the new technologies also work by electrical and mechanical process",["4_tech_how3.wav"]]
            },
            "why,how,what":{ // #5 switched how and what from #4
                "alien,why":["the aliens are here to make different electrical components",["4_aliens_why1.wav"]],
                "plant,why":["the robotic plants create electrical components",["4_robotic_plants_why1.wav"]],
                "tech,why":["the telecsope is here to find electrical components",["4_telescope_why1.wav"]],
                "reason_1,why":["the chips are here to build different electrical components",["4_chips_why1.wav"]],
                "reason_2,why":["the light catchers are here to produce electrical components",["4_light_why1.wav"]],
                "reason_3,why":["the new technologies are here to create different electrical components",["4_tech_why1.wav"]],

                "alien,how":["the aliens work by eletrical chips",["4_aliens_how2.wav"]],
                "plant,how":["the plants work by light manipulation",["4_robotic_plants_how2.wav"]],
                "tech,how":["the telescope works by new technologies",["4_telescope_how2.wav"]],
                "reason_1,how":["the chips are powered by high processing power",["4_chips_how2.wav"]],
                "reason_2,how":["the the light catchers are powered by light harvested form the sun",["4_light_how2.wav"]],
                "reason_3,how":["the new technologies are powered by forces from the stars",["4_tech_how2.wav"]],

                "alien,what":["the aliens are made of electrical and mechanical process",["4_aliens_what3.wav"]],
                "plant,what":["the robotic plants are made of electrical and mechanical process",["4_robotic_plants_what3.wav"]],
                "tech,what":["the telescope is made of new electrical and mechanical process",["4_telescope_what3.wav"]],
                "reason_1,what":["the chips are made of electrical and mechanical process",["4_chips_what3.wav"]],
                "reason_2,what":["the light catchers are made from electrical and mechanical process",["4_light_what3.wav"]],
                "reason_3,what":["the new technologies are made of electrical and mechanical process",["4_tech_what3.wav"]] 
            }
        },
        "background":"app4_background.png",
        "dir":"items/world4/",
        "concepts":{
            "reason_1":{"image":["alien_reason.png"],"level":2,"pos":"0.67, 0.46","size":"0.075, 0.087"},
            "reason_3":{"image":["tech_reason.png"],"level":2,"pos":"0.45, 0.8","size":"0.13, 0.2"},
            "reason_2":{"image":["plant_reason.png"],"level":2,"pos":"0.77, 0.485","size":"0.1, 0.1"},
            "reason_5":{"image":["alien_reason.png"],"level":2,"pos":"0.67, 0.46","size":"0.075, 0.087"},
            "reason_4":{"image":["alien_reason.png"],"level":2,"pos":"0.67, 0.46","size":"0.075, 0.087"},
            "process_5":{"image":["processes6.png"],"level":2,"pos":"0.24, 0.52","size":"0.15, 0.13"},
            "process_4":{"image":["processes5.png"],"level":2,"pos":"0.37, 0.52","size":"0.13, 0.12"},
            "process_3":{"image":["processes4.png"],"level":2,"pos":"0.14, 0.5","size":"0.14, 0.12"},
            "process_2":{"image":["processes3.png"],"level":2,"pos":"0.1, 0.58","size":"0.13, 0.1"},
            "process_1":{"image":["processes2.png"],"level":2,"pos":"0.04, 0.5","size":"0.1, 0.1"},
            "process_extend_3":{"image":["processes2.png"],"level":2,"pos":"0.04, 0.5","size":"0.1, 0.1"},
            "process_extend_2":{"image":["processes2.png"],"level":2,"pos":"0.04, 0.5","size":"0.1, 0.1"},
            "process_extend_1":{"image":["processes2.png"],"level":2,"pos":"0.04, 0.5","size":"0.1, 0.1"},
            "plant":{"image":["plant_app4.png"],"level":1,"pos":"0.103, 0.25","size":"0.167, 0.240"},
            "part_extend_2":{"image":["electrical_comp2.png"],"level":2,"pos":"0.52, 0.53","size":"0.1, 0.12"},
            "part_extend_3":{"image":["electrical_comp2.png"],"level":2,"pos":"0.52, 0.53","size":"0.1, 0.12"},
            "part_extend_1":{"image":["electrical_comp2.png"],"level":2,"pos":"0.52, 0.53","size":"0.1, 0.12"},
            "reason_extend_1":{"image":["chip_reason.png"],"level":3,"pos":"0.85, 0.33","size":"0.172, 0.268"},
            "alien":{"image":["alien_app4.png"],"level":1,"pos":"0.3, 0.3","size":"0.397, 0.45"},
            "reason_extend_3":{"image":["technologies_reason.png"],"level":2,"pos":"0.9, 0.9","size":"0.162, 0.243"},
            "reason_extend_2":{"image":["light_reason.png"],"level":3,"pos":"0.1, 0.9","size":"0.16, 0.208"},
            "tech":{"image":["tech_app4.png"],"level":1,"pos":"0.5, 0.3","size":"0.323, 0.405"},
            "part_1":{"image":["electrical_comp2.png"],"level":2,"pos":"0.52, 0.53","size":"0.1, 0.12"},
            "part_2":{"image":["electrical_comp3.png"],"level":2,"pos":"0.86, 0.5","size":"0.09, 0.09"},
            "part_3":{"image":["electrical_comp8.png"],"level":2,"pos":"0.625, 0.555","size":"0.1, 0.12" },
            "part_4":{"image":["electrical_comp10.png"],"level":2,"pos":"0.74, 0.57","size":"0.08, 0.1"},
            "part_5":{"image":["electrical_comp12.png"],"level":2,"pos":"0.84, 0.57","size":"0.08, 0.1"}
        }
    },
    "network_5":{
        "story":{
            "what,why,how":{ // original
                "plant,what":["the thorny plants are made out of crystals",["5_thorn_plants_what1.wav"]],
                "alien,what":["the aliens are made of crystals",["5_aliens_what1.wav"]],
                "tech,what":["the spacecraft is made out of crystals",["5_spaceship_what1.wav"]],
                "reason_1,what":["the ultimate factory is built out of crystals",["5_ulti_factory_what1.wav"]],
                "reason_2,what":["the predators are made out of crystals",["5_predators_what1.wav"]],
                "reason_3,what":["the endangered species are made out of crystals",["5_endangered_what1.wav"]],

                "plant,why":["the thorny plants are here to protect against predators",["5_thorn_plants_why2.wav"]],
                "alien,why":["the aliens are here to build the ultimate factory",["5_aliens_why2.wav"]],
                "tech,why":["the spacecraft is here to transport endangered species",["5_spaceship_why2.wav"]], 
                "reason_1,why":["the factory is here to produce the pyramid crystal",["5_ulti_factory_why2.wav"]],
                "reason_2,why":["the predators are here to eat all the birds",["5_predators_why2.wav"]],
                "reason_3,why":["the endangered species are dwindeling because of polluting factories",["5_endangered_why2.wav"]],

                "plant,how":["the plants work by internal rainbow processes",["5_thorn_plants_how3.wav"]],
                "alien,how":["the aliens work by spiraling rainbow processes",["5_aliens_how3.wav"]],
                "tech,how":["the spacecraft works by harnessing the rainbow processes",["5_spaceship_how3.wav"]],
                "reason_1,how":["the factory work by harnessing the rainbow processes",["5_ulti_factory_how3.wav"]],
                "reason_2,how":["the predators work by internal dynamic processes",["5_predators_how3.wav"]],
                "reason_3,how":["the endangered species work by internal spiraling processes",["5_endangered_how3.wav"]]               
            },
            "what,how,why":{ // #1 switched why and how from original 
                "plant,what":["the thorny plants are made out of crystals",["5_thorn_plants_what1.wav"]],
                "alien,what":["the aliens are made of crystals",["5_aliens_what1.wav"]],
                "tech,what":["the spacecraft is made out of crystals",["5_spaceship_what1.wav"]],
                "reason_1,what":["the ultimate factory is built out of crystals",["5_ulti_factory_what1.wav"]],
                "reason_2,what":["the predators are made out of crystals",["5_predators_what1.wav"]],
                "reason_3,what":["the endangered species are made out of crystals",["5_endangered_what1.wav"]],

                "plant,how":["the thorny plants grow from the slime of predators",["5_thorn_plants_how2.wav"]],
                "alien,how":["the aliens work from mechanical parts made in the factory",["5_aliens_how2.wav"]],
                "tech,how":["the spacecraft can only fly with the help of endangered species",["5_spaceship_how2.wav"]], 
                "reason_1,how":["the factory works with the energy of the pyramid crystal",["5_ulti_factory_how2.wav"]],
                "reason_2,how":["the predators work by processes they steal from the birds",["5_predators_how2.wav"]],
                "reason_3,how":["the endangered species can only live if there is no pollution from the factories",["5_endangered_how2.wav"]],

                "plant,why":["the plants are here to create rainbow discs",["5_thorn_plants_why3.wav"]],
                "alien,why":["the aliens are here to collect rainbow discs",["5_aliens_why3.wav"]],
                "tech,why":["the spacecraft is here to help the aliens catch the rainbow discs",["5_spaceship_why3.wav"]],
                "reason_1,why":["the factory is here to create rainbow discs",["5_ulti_factory_why3.wav"]],
                "reason_2,why":["the predators are here to destroy the rainbow discs",["5_predators_why3.wav"]],
                "reason_3,why":["the endangered species are here to hide the rainbow discs",["5_endangered_why3.wav"]]               
            },
            "why,what,how":{ // #2 switched why and what from original
                "plant,why":["the thorny plants are here to hide the crystals",["5_thorn_plants_why1.wav"]],
                "alien,why":["the aliens are here to find expensive crystals",["5_aliens_why1.wav"]],
                "tech,why":["the spacecraft is here to help the aliens move the crystals",["5_spaceship_why1.wav"]],
                "reason_1,why":["the ultimate factory is here to make crystals",["5_ulti_factory_why1.wav"]],
                "reason_2,why":["the predators are here to destroy the crystals",["5_predators_why1.wav"]],
                "reason_3,why":["the endangered species are here to eat crystals",["5_endangered_why1.wav"]],

                "plant,what":["the thorny plants are made of the predators poop",["5_thorn_plants_what2.wav"]],
                "alien,what":["the aliens are made of materials from the factory",["5_aliens_what2.wav"]],
                "tech,what":["the spacecraft is made of rocks that the endangered species create",["5_spaceship_what2.wav"]], 
                "reason_1,what":["the factory is made of pyramid crystals",["5_ulti_factory_what2.wav"]],
                "reason_2,what":["the predators are made of old bird bones",["5_predators_what2.wav"]],
                "reason_3,what":["the endangered species are made of special materials from the factories",["5_endangered_what2.wav"]],

                "plant,how":["the plants work by internal rainbow processes",["5_thorn_plants_how3.wav"]],
                "alien,how":["the aliens work by spiraling rainbow processes",["5_aliens_how3.wav"]],
                "tech,how":["the spacecraft works by harnessing the rainbow processes",["5_spaceship_how3.wav"]],
                "reason_1,how":["the factory work by harnessing the rainbow processes",["5_ulti_factory_how3.wav"]],
                "reason_2,how":["the predators work by internal dynamic processes",["5_predators_how3.wav"]],
                "reason_3,how":["the endangered species work by internal spiraling processes",["5_endangered_how3.wav"]]               
            },
            "why,how,what":{ // #3 switched how and what from #2
                "plant,why":["the thorny plants are here to hide the crystals",["5_thorn_plants_why1.wav"]],
                "alien,why":["the aliens are here to find expensive crystals",["5_aliens_why1.wav"]],
                "tech,why":["the spacecraft is here to help the aliens move the crystals",["5_spaceship_why1.wav"]],
                "reason_1,why":["the ultimate factory is here to make crystals",["5_ulti_factory_why1.wav"]],
                "reason_2,why":["the predators are here to destroy the crystals",["5_predators_why1.wav"]],
                "reason_3,why":["the endangered species are here to eat crystals",["5_endangered_why1.wav"]],

                "plant,how":["the thorny plants grow from the slime of predators",["5_thorn_plants_how2.wav"]],
                "alien,how":["the aliens work from mechanical parts made in the factory",["5_aliens_how2.wav"]],
                "tech,how":["the spacecraft can only fly with the help of endangered species",["5_spaceship_how2.wav"]], 
                "reason_1,how":["the factory works with the energy of the pyramid crystal",["5_ulti_factory_how2.wav"]],
                "reason_2,how":["the predators work by processes they steal from the birds",["5_predators_how2.wav"]],
                "reason_3,how":["the endangered species can only live if there is no pollution from the factories",["5_endangered_how2.wav"]],

                "plant,what":["the plants are made of internal rainbow processes",["5_thorn_plants_what3.wav"]],
                "alien,what":["the aliens are made of spiraling rainbow processes",["5_aliens_what3.wav"]],
                "tech,what":["the spacecraft is made of complex rainbow processes",["5_spaceship_what3.wav"]],
                "reason_1,what":["the factory work is made of millions of rainbow processes",["5_ulti_factory_what3.wav"]],
                "reason_2,what":["the predators are made of internal dynamic processes",["5_predators_what3.wav"]],
                "reason_3,what":["the endangered species are made of internal spiraling processes",["5_endangered_what3.wav"]]                 
            },
            "how,why,what":{ // #4 switched how and what from original
                "plant,how":["the thorny grow with the power from the crystals",["5_thorn_plants_how1.wav"]],
                "alien,how":["the aliens live of the power of the crystals",["5_aliens_how1.wav"]],
                "tech,how":["the spacecraft can fly with the energy from the crystals",["5_spaceship_how1.wav"]],
                "reason_1,how":["the ultimate factory works with the energy from the crystals",["5_ulti_factory_how1.wav"]],
                "reason_2,how":["the predators work with power from the crystals",["5_predators_how1.wav"]],
                "reason_3,how":["the endangered species can swim by eating the crystals",["5_endangered_how1.wav"]],

                "plant,why":["the thorny plants are here to protect against predators",["5_thorn_plants_why2.wav"]],
                "alien,why":["the aliens are here to build the ultimate factory",["5_aliens_why2.wav"]],
                "tech,why":["the spacecraft is here to transport endangered species",["5_spaceship_why2.wav"]], 
                "reason_1,why":["the factory is here to produce the pyramid crystal",["5_ulti_factory_why2.wav"]],
                "reason_2,why":["the predators are here to eat all the birds",["5_predators_why2.wav"]],
                "reason_3,why":["the endangered species are dwindeling because of polluting factories",["5_endangered_why2.wav"]],

                "plant,what":["the plants are made of internal rainbow processes",["5_thorn_plants_what3.wav"]],
                "alien,what":["the aliens are made of spiraling rainbow processes",["5_aliens_what3.wav"]],
                "tech,what":["the spacecraft is made of complex rainbow processes",["5_spaceship_what3.wav"]],
                "reason_1,what":["the factory work is made of millions of rainbow processes",["5_ulti_factory_what3.wav"]],
                "reason_2,what":["the predators are made of internal dynamic processes",["5_predators_what3.wav"]],
                "reason_3,what":["the endangered species are made of internal spiraling processes",["5_endangered_what3.wav"]]               
            },
            "how,what,why":{ // #5 switched why and what from #4
                "plant,how":["the thorny grow with the power from the crystals",["5_thorn_plants_how1.wav"]],
                "alien,how":["the aliens live of the power of the crystals",["5_aliens_how1.wav"]],
                "tech,how":["the spacecraft can fly with the energy from the crystals",["5_spaceship_how1.wav"]],
                "reason_1,how":["the ultimate factory works with the energy from the crystals",["5_ulti_factory_how1.wav"]],
                "reason_2,how":["the predators work with power from the crystals",["5_predators_how1.wav"]],
                "reason_3,how":["the endangered species can swim by eating the crystals",["5_endangered_how1.wav"]],

                "plant,what":["the thorny plants are made of the predators poop",["5_thorn_plants_what2.wav"]],
                "alien,what":["the aliens are made of materials from the factory",["5_aliens_what2.wav"]],
                "tech,what":["the spacecraft is made of rocks that the endangered species create",["5_spaceship_what2.wav"]], 
                "reason_1,what":["the factory is made of pyramid crystals",["5_ulti_factory_what2.wav"]],
                "reason_2,what":["the predators are made of old bird bones",["5_predators_what2.wav"]],
                "reason_3,what":["the endangered species are made of special materials from the factories",["5_endangered_what2.wav"]],

                "plant,why":["the plants are here to create rainbow discs",["5_thorn_plants_why3.wav"]],
                "alien,why":["the aliens are here to collect rainbow discs",["5_aliens_why3.wav"]],
                "tech,why":["the spacecraft is here to help the aliens catch the rainbow discs",["5_spaceship_why3.wav"]],
                "reason_1,why":["the factory is here to create rainbow discs",["5_ulti_factory_why3.wav"]],
                "reason_2,why":["the predators are here to destroy the rainbow discs",["5_predators_why3.wav"]],
                "reason_3,why":["the endangered species are here to hide the rainbow discs",["5_endangered_why3.wav"]]               
            },
        },
        "background":"app5_background.png",
        "dir":"items/world5/",
        "concepts":{
            "reason_1":{"image":["alien_reason.png"],"level":2,"pos":"0.55, 0.45","size":"0.15, 0.22"},
            "reason_3":{"image":["spaceship_reason.png"],"level":2,"pos":"0.89, 0.155","size":"0.2, 0.18"},
            "reason_2":{"image":["plant_reason.png"],"level":2,"pos":"0.64, 0.34","size":"0.12, 0.12"},
            "reason_5":{"image":["alien_reason.png"],"level":2,"pos":"0.55, 0.45","size":"0.15, 0.22"},
            "reason_4":{"image":["alien_reason.png"],"level":2,"pos":"0.55, 0.45","size":"0.15, 0.22"},
            "process_5":{"image":["what_cell21.png"],"level":2,"pos":"0.33, 0.9","size":"0.161, 0.161"},
            "process_4":{"image":["what_cell20.png"],"level":2,"pos":"0.2, 0.9","size":"0.161, 0.161"},
            "process_3":{"image":["what_cell8png.png"],"level":2,"pos":"0.07, 0.9","size":"0.161, 0.161"},
            "process_2":{"image":["what_cell1.png"],"level":2,"pos":"0.46, 0.9","size":"0.161, 0.161"},
            "process_1":{"image":["what_cell _2.png"],"level":2,"pos":"0.59, 0.9","size":"0.161, 0.161"},
            "process_extend_3":{"image":["what_cell21.png"],"level":2,"pos":"0.33, 0.9","size":"0.161, 0.161"},
            "process_extend_2":{"image":["what_cell21.png"],"level":2,"pos":"0.33, 0.9","size":"0.161, 0.161"},
            "process_extend_1":{"image":["what_cell21.png"],"level":2,"pos":"0.33, 0.9","size":"0.161, 0.161"},
            "plant":{"image":["app5_plant.png"],"level":1,"pos":"0.595, 0.248","size":"0.1, 0.15"},
            "part_extend_2":{"image":["crystals7.png"],"level":2,"pos":"0.27, 0.6","size":"0.12, 0.12"},
            "part_extend_3":{"image":["crystals7.png"],"level":2,"pos":"0.27, 0.6","size":"0.12, 0.12"},
            "part_extend_1":{"image":["crystals7.png"],"level":2,"pos":"0.27, 0.6","size":"0.12, 0.12"},
            "reason_extend_1":{"image":["factory_reason.png"],"level":3,"pos":"0.54, 0.63","size":"0.2, 0.25"},
            "alien":{"image":["app5_alien.png"],"level":1,"pos":"0.83, 0.45","size":"0.2, 0.383"},
            "reason_extend_3":{"image":["whale_reason.png"],"level":2,"pos":"0.38, 0.35","size":"0.23, 0.3"},
            "reason_extend_2":{"image":["predator_reason.png"],"level":3,"pos":"0.85, 0.85","size":"0.196, 0.191"},
            "tech":{"image":["app5_TECH.png"],"level":1,"pos":"0.7, 0.7","size":"0.154, 0.199"},
            "part_1":{"image":["crystals5_1.png"],"level":2,"pos":"0.069, 0.73","size":"0.12, 0.12"},
            "part_2":{"image":["crystals6_1.png"],"level":2,"pos":"0.16, 0.66","size":"0.12, 0.12"},
            "part_3":{"image":["crystals7.png"],"level":2,"pos":"0.27, 0.6","size":"0.12, 0.12"},
            "part_4":{"image":["crystals10.png"],"level":2,"pos":"0.058, 0.643","size":"0.13, 0.13"},
            "part_5":{"image":["crystals12.png"],"level":2,"pos":"0.145, 0.575","size":"0.13, 0.13"}
        }
    }
};
